### ISSUE TITLE
[Custom Logo Build]: Chrome OS logo system google

### ISSUE THREAD

**Issue by crisutf** [ChocolateLoverRaj/scripts#7] opened 2023-10-09 04:16 UTC
### Board Name

Blooguard

### Logo

![My Custom Coreboot Logo](https://github.com/ChocolateLoverRaj/scripts/assets/52586855/844ef682-6a4b-4b46-8440-fc8948b939a5)

**Comment by ChocolateLoverRaj** [comment] 2023-10-09 04:45
Duplicate of #6

**Closed as not planned by ChocolateLoverRaj** 2023-10-09 04:45 UTC
Labels: failure, build, build-full-rom
